title: Willian Justen - Desenvolvedor Front End
description: A blog about lorem ipsum dolor sit amet
baseurl: ''
url: ''
username: Lorem Ipsum
user_description: Anon Developer at Lorem Ipsum Dolor
email: anon@anon.com
twitter_username: lorem_ipsum
github_username: lorem_ipsum
gplus_username: lorem_ipsum
disqus_username: lorem_ipsum
markdown: kramdown
highlighter: rouge
permalink: '/:title/'
compress_html:
  clippings: all
  comments: all
  endings: []
  profile: false
links:
  - title: Home
    url: /
  - title: Series
    url: /series
  - title: Tags
    url: /tags
  - title: About Me
    url: /about
exclude:
  - package.json
  - src
  - node_modules
